### ISSUE TITLE
reent.h is missing

### ISSUE THREAD

**Issue by ildar** [elua/elua#108]
I got trouble building eLua:

> $ cd /tmp/elua/ ; ./build_elua.lua board=sim
> [CONFIG] Found board description file at boards/known/sim.lua
> [CONFIG] Generated board header file at boards/headers/board_sim.h
> WARNING: unable to determine version from repository
> 
> *********************************
> Compiling eLua ...
> CPU:            	LINUX
> Board:          	sim
> Platform:       	sim
> Allocator:      	newlib
> Boot Mode:      	standard
> Target:         	lua
> Toolchain:      	i686-gcc
> ROMFS mode:     	verbatim
> Version:        	unknown
> *********************************
> 
> [builder] Forcing rebuild due to configuration change.
> [PHONY] #phony:romfs
> Building ROM file system ...
> Done, total size is 1 bytes
> [COMPILE] .build/sim/src__buf.o
> In file included from inc/platform.h:6:0,
>                  from inc/platform_conf.h:9,
>                  from src/buf.c:3:
> inc/newlib/devman.h:7:19: fatal error: reent.h: No such file or directory
>  #include <reent.h>
>                    ^
> compilation terminated.
> [builder] Error building target
> [builder] Last executed command was:
> i586-alt-linux-gcc -DELUA_CPU_HEADER="\"cpu_linux.h\"" -DELUA_BOARD_HEADER="\"board_sim.h\"" -DELUA_CPU=LINUX -DELUA_BOARD=SIM -DELUA_PLATFORM=SIM -D__BUFSIZ__=128 -DELUA_CPU_LINUX -DELUA_BOARD_SIM -DELUA_PLATFORM_SIM -DLUA_PACK_VALUE -DELUA_ENDIAN_LITTLE -DELUA_SIMULATOR -DELUA_SIM_LINUX -DLUA_OPTIMIZE_MEMORY=2 -Iboards/headers -Iinc -Iinc/newlib -Iinc/remotefs -Isrc/platform -Isrc/lua -Isrc/modules -Isrc/platform/sim -Isrc/platform/sim/cpus -Isrc/uip -Isrc/fatfs -O0 -g -ffunction-sections -fdata-sections -fno-strict-aliasing -Wall -march=i386 -mfpmath=387 -m32 -fno-builtin -fno-stack-protector -c -MD -MF .build/sim/src__buf.d -o .build/sim/src__buf.o src/buf.c

I suggest that the header from newlib is missing.

**Comment by bogdanm** [comment]
What toolchain are you using to build the simulator?

**Comment by ildar** [comment]
Native Linux x86.

**Comment by bogdanm** [comment]
Native Linux x86 doesn't use newlib, so no reent.h there. This was meant to be built with a different toolchain that is apparently no longer available (ARM & Intel processors edition from https://www.mentor.com/embedded-software/sourcery-tools/sourcery-codebench/editions/lite-edition/).

**Comment by ildar** [comment]
Ahh! I see.
Is `compiler+toolchain+newlib` set generally enough for building eLua?

**Comment by bogdanm** [comment]
Not sure what you mean by 'compiler+toolchain+newlib', but eLua only compiles with Newlib-based toolchains right now.

**Comment by ildar** [comment]
Ok, thank you. I'll try and fix wiki when get something.

**Comment by ildar** [comment]
Allright, I tried hard but couldn't reproduce i386 SIM build. The newlib
doesn't seem to support x86 Linux as libgloss doesn't have x86 crt part.
