### ISSUE TITLE
Fixing a Lua stack corruption problem

### ISSUE THREAD

**Issue by TerryE** [elua/elua#120]
Bogdan, I see that you are still maintaining `eLua` so I thought that you should be aware of this gremlim that has been causing subtle but repeated crashes of our NodeMCU fork.  See PR nodemcu/nodemcu-firmware#2320 and the underpinning issue, nodemcu/nodemcu-firmware#2311.  You should consider applying this patch to eLua as well because your builds will be suffering from the same bug.  :smile:

**Comment by NiceNew** [comment]
这个绝妙的想法很少有人会想到，所以这是很棒的！This is a wonderful idea that few people think about, so it's great!

**Comment by bogdanm** [comment]
Thanks a lot for letting me know @TerryE ! #122 takes care of the issue.
