### ISSUE TITLE
Temp buffer allocates 16 bytes instead of 4

### ISSUE THREAD

**Issue by francisconroy** [elua/elua#164]
Please see https://github.com/elua/elua/blob/566df8a065e7d8e9d6089f6b20c4bc8dcd61ec38/src/lua/ldump.c#L154

The code which swaps the upper and lower dwords allocates char* temp[4]; as the temp buffer. 
Each element in the temp array will be as wide as the memory bus.. whereas it only needs to be of length sizeof(double)/2.

**Comment by bogdanm** [comment]
Not sure what you mean. In the declaration above `sizeof(temp)` is 4. When declaring pointers in C, the `*` binds to the variable, not to the type.

**Comment by francisconroy** [comment]
Yes, you are correct. I've done some learning since this..
