### ISSUE TITLE
Is NTFS and EXT4 supported?

### ISSUE THREAD

**Issue by Shadowblitz16** [elua/elua#168]
Does this support NTFS and EXT4 or can we add support on our own?

**Comment by bogdanm** [comment]
If I understand correctly, you're asking if NTFS/EXT4 are supported options for the SD card file system? They are not. Personally I am not aware of any NTFS/EXT4 implementation that is small enough to run on such resource constained devices.

**Comment by Shadowblitz16** [comment]
oh so this couldn't be used for raspberry pi os dev then

**Comment by bogdanm** [comment]
It probably could with some serious tweaking, but with a Pi you're probably much better off with stock Lua.

**Comment by Shadowblitz16** [comment]
ok thankyou
