### ISSUE TITLE
Codepath in EGC patch missed.

### ISSUE THREAD

**Issue by TerryE** [elua/elua#74]
Hi, I am a committer on the nodeMCU implementation and we've found a hole in the EGC fixes, see issue issue nodemcu/nodemcu-firmware#795 and the fix PR nodemcu/nodemcu-firmware#812. I've traced this omission back to the EGC patch.  At a patch level this should be directly applicable to eLua

Sorry for not giving this as a native eLua patch, but I don't have a test-bed for standard eLua, just esp8266 modules.

Regards Terry

**Comment by TerryE** [comment]
@bogdanm  @jsnyder any comments?

**Comment by bogdanm** [comment]
Hi @TerryE, thanks. Your patch looks good to me, although I'm not that familiar with the inner working of the EGC. But if it works for you, that's a strong indication that it should be part of eLua too. Do you want to open a PR against eLua, or do you want me to merge it manually? Either is fine with me.

**Comment by TerryE** [comment]
As I said, it's been well tested on our nodemcu fork and has solved a few stability issues.  The issue that I have is that nodemcu is a fork and has diverged from eLua somewhat -- partly because of the necessities of working within the strictures of the Espressif SDK, and partly for historic reasons that I don't agree with.  However, the result is the eLua is different enough to merit its own retesting.  But doing this just isn't straight forward.  I have found it impractical to get a minimal eLua to work as a native host image,  because of the incompatibilities of the posix libraries and the newlib-based ELF  (though it would help if you had a test set up that would work on a VBox VM, say).  So wehat I am saying is that I would prefer you to do a manual merge.

On a separate point (and breaking issue etiquette, sorry) are you interested in this: [Lua Compact Debug (LCD)](http://www.esp8266.com/wiki/doku.php?id=nodemcu-LCD).  What this patch does is to eliminate 90% of the overhead of using lua source execution rather than stripped binary luac.cross files.  It's also stable on nodeMCU.  If you are interest I can raise another issue.

**Comment by bogdanm** [comment]
There is an eLua "simulator" that you can run under Linux, but it's not well documented. I've used it quite extensively while developing the LTR patch.
About LCD, yes, that sounds quite interesting. Please open a separate issue about it.

**Comment by shaiku** [comment]
Here's the patch for your convenience, bogdanm.
[EGC_stack_fix.patch.txt](https://github.com/elua/elua/files/678453/EGC_stack_fix.patch.txt)

I can vouch for this change as it cured a crash I had with eLua after merging over only one line of code from Lua 5.1.5 (a call to luaD_checkstack).  There's a real bug this is addressing and it's going to bite somebody else sooner or later.

**Comment by bogdanm** [comment]
Patch now integrated, thanks!
