### ISSUE TITLE
Possible memory leak if lua code contains error

### ISSUE THREAD

**Issue by emilsedemil** [elua/elua#92]
I believe there is a memory leak in the code. 

Within the file lparser.c in the function static void block, the variable pbl is dynamically allocated. This is obviously an optimization to decrease the memory usage, unfortunately I believe it is not the optimal solution.

The function block can throw an exception (LUAI_THROW in luaD_throw) which will be handled from luaD_rawrununprotected. The consequence is that this function is "jumped" and the deallocation of pbl with it.

This happens when there is a malformed piece of code e.g.:
"""
prog = [[
do
   function foo();
     return
   end
end
]]

do 
   pcall(loadstring(prog))
end 
"""

**Comment by shaiku** [comment]
block() calls chunk(), chuck() calls enterlevel(), enterlevel() calls "luaX_lexerror(ls, "chunk has too many syntax levels", 0);" which throws the exception and jumps back to luaD_rawrununprotected() without freeing the memory.

I'd say you are right!

**Comment by bogdanm** [comment]
Commit 854cb148852bdbd4d39ec4e18ffe35ab95558165 should take care of this issue.
